server:
  port: 9000


spring:
  profiles:
    active: usrRegistration
---
spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin123#BrijeshChauhan12
    url: jdbc:mysql://localhost:3306/usrRegistration
    username: admin
  jpa:
    show-sql: true

