server:
  port: 8768


spring:
  profiles:
    active: usrRegistration
---
spring:
  profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin123#BrijeshChauhan12
    url: jdbc:mysql://localhost:3306/usrRegistration
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8768/login/oauth2/code/{registrationId}"
            scope: profile
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8768/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000

welcome:
  message: Welcome to spring world in usrRegistration

#---
#
#spring:
#  profile: qa
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: admin123#BrijeshChauhan12
#    url: jdbc:mysql://localhost:3306/ET-QA
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#welcome:
#  message: Welcome to spring world in qa

#---
#
#spring:
#  profile: prod
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: admin123#BrijeshChauhan12
#    url: jdbc:mysql://localhost:3306/ET-PROD
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: update
#welcome:
#  message: Welcome to spring world in prod
